### ISSUE TITLE
Shouldn't Text class >> #fromSton: be on 'Ston-Text-Support' ?

### ISSUE THREAD

**Issue by marianopeck** [svenvc/ston#23]
Hi Sven,

The 2 instance side extensions on Text are from  'STON-Text-Support' , however, the class side `fromSton:' is in 'STON-Core'. I think it should also be 'STON-Text-Support', right? 

Cheers,

**Comment by svenvc** [comment]
Right, that was an error

https://github.com/svenvc/ston/commit/6a0ad04b877a425e0afa07772b08ee54c30a305a

should fix it

**Comment by marianopeck** [comment]
Thanks Sven!
