### ISSUE TITLE
STON is not cycle-proof

### ISSUE THREAD

**Issue by dalehenrich** [svenvc/ston#3]
I have run into some object graphs that end up in infinite loops during deserialization.

I haven't completely characterized the actual graph (it's pretty complex), but it appears that there are several points in the graph that refer back to the one of the root objects ... at the end of the initial pass there are one or more unresolvedReferences and because the graph is self referential the traversal looking to replace the unresolved references never terminates ...

As I think about there are probably two separate self-referential paths ... one reference is resolved and then the second path is followed which leads to the first self  unresolved reference (now resolved) and we're off to the races ...

**Comment by svenvc** [comment]
Cycles are fixed, AFAIK
Text has a custom serializer.
Closing for now.
