### ISSUE TITLE
Color values lose precision when serialized

### ISSUE THREAD

**Issue by webwarrior-ws** [svenvc/ston#36]
There is unnecessary rounding of values in `Color>>#stonOn:` that causes Color instances to not be the same after serialize/materialize roundtrip.
However issue #34 must also be addressed for any Color instance to be truly equal to itself after roundtrip, because alpha is stored as a float.

**Comment by svenvc** [comment]
Yes, you are right.

I implemented your suggestion in https://github.com/svenvc/ston/commit/a9959114c3036aad1dd5c327a5b8ac3309e4c3e5
