### ISSUE TITLE
Improve method comments

### ISSUE THREAD

**Issue by Ducasse** [svenvc/ston#38]
Hi sven 

after losing some moment trying to output a dictionary, I felt that improving the comments of put:* would be good.

```
STON class >> put: aDictionary onStream: stream
	"Put aDictinoary into the argument, stream.
	Here is a typical scenario
	
	| wrt |
	wrt := (FileSystem workingDirectory / 'pillar.xxx') writeStream.
	STON 
		put: (Dictionary new at: #a put: 33; yourself)
		onStream: wrt.
	wrt close
	
	Notice the close of the stream that will flush the output in the file.
	"
	(self writer on: stream) nextPut: aDictionary
```

I can do a PR if needed.
S.

**Comment by svenvc** [comment]
Although the class comment of the STON class is pretty extensive, the methods on the class side have indeed no comments. 

I will do a pass over them and add some examples as well.

But not now, as I am on holiday.

**Comment by Ducasse** [comment]
Good holidays. 
They are important :) I should take some more.

**Comment by svenvc** [comment]
Hi Stef,

I just committed the following: https://github.com/svenvc/ston/commit/81b28d9cc1e2056cd4ea9b7332377e54c08e161c

Sven
