### ISSUE TITLE
STON incorrectly converts instances of Interval

### ISSUE THREAD

**Issue by dalehenrich** [svenvc/ston#5]
Admittedly I have not updated to the latest version of STON, so if it this is fixed great!

Otherwise, it appears that STON does not handle Interval instances correctly as the following throws an error in Pharo1.4:

...Smalltalk
STON fromString: (STON toString: (3 to: 6))
...

Apparently STON turns an interval into a collection:
...Smalltalk
 'Interval[3,4,5,6]'
...
which doesn't seem correct ...

Dale

**Comment by svenvc** [comment]
Interval is a PIA, it is more like a fake collection.
I will consider adding a special case to not treat it like a collection.
Maybe there should be some easy mechanism to add exceptions.

**Comment by dalehenrich** [comment]
Yes, it is worth waiting and letting the problem marinate when you hit these odd corner cases ... the "best" solution is not always obvious ...

Does it seem that in these exceptional cases the "fallback" is to simply record and pass along the state? Interval is a subclass of SequenceableCollection for behavior reasons not state ...

**Comment by svenvc** [comment]
I added support for Interval upstream, will arrive later in git
